### PR TITLE
Adjust app to new design specs

### LINKED ISSUE #13: Adjust to new design spec
Adjust the app to the new design specs. The changes include:

- Navigation bar in onboarding now has an icon
- New icons in onboarding
- Change button radii
- Change fuel type selection to radio buttons
- Adjustments to list items and hamburger menu

### PR DESCRIPTION
**Pull request by telip007**
Adjusted the app to the new design specs.

- Navigation bar in onboarding now has an icon
- New icons in onboarding
- Change button radii
- Change fuel type selection to radio buttons
- Adjustments to list items and hamburger menu

| List  |  Fuel type selection  | Menu  |  Onboarding  |
|---|---|---|---|
| Simulator Screen Shot - iPhone 13 Pro - 2022-08-09 at 16 18 54  |  Simulator Screen Shot - iPhone 13 Pro - 2022-08-09 at 16 19 02 | Simulator Screen Shot - iPhone 13 Pro - 2022-08-09 at 16 19 07  | Simulator Screen Shot - iPhone 13 Pro - 2022-08-09 at 16 19 13 |

Closes #13

### CODE REVIEW

**Comment by EmDee** [comment]
We should align the fuel prices to the top of the navigation/fueling button, otherwise it will jump around too much

grafik

**Comment by telip007** [comment]
> We should align the fuel prices to the top of the navigation/fueling button, otherwise it will jump around too much
> 
> 
> 
> 
> 
> 

Actually it is aligned to the top of the address label (as in the design). Shouldn't really jump too much around, should it? 🤔

**Comment by EmDee** [comment]
Let me talk to our chief designer. My first impression was that it looks off when the spacing between the bottom button and the price box differs.

**Comment by EmDee** [comment]
Master designer said he tried different options and all had some disadvantages. Aligning to the top of the address it is then.

**Pull request merged**
