### PR TITLE
Proposal: Remove storyboards & BartyCrouch dependency

### PR DESCRIPTION
**Pull request by telip007**
Removed all storyboards and therefore also the BartyCrouch dependency.

Some points why we should remove storyboards:

- Sometimes Xcode has its problems with Storyboards even when they are small
- Merging Storyboards can be a pain
- Hard to review changes in them

### CODE REVIEW

**Comment by EmDee** [comment]
In the onboarding the `ButtonView`'s seems to have conflicting constraints:

```
constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000023dc190 App.ButtonView:0x159c60600.height == 50   (active)>",
    "<NSLayoutConstraint:0x6000023dc550 '_UITemporaryLayoutHeight' App.ButtonView:0x159c60600.height == 0   (active)>"
)
```

**Comment by EmDee** [comment]
Also: Please create a follow-up ticket to add the new menu layout in this base app as well.

**Comment by EmDee** [comment]
@telip007 Ping

**Comment by telip007** [comment]
> In the onboarding the `ButtonView`'s seems to have conflicting constraints:
> 
> ```
> constraints and fix it. 
> (
>     "<NSLayoutConstraint:0x6000023dc190 App.ButtonView:0x159c60600.height == 50   (active)>",
>     "<NSLayoutConstraint:0x6000023dc550 '_UITemporaryLayoutHeight' App.ButtonView:0x159c60600.height == 0   (active)>"
> )
> ```

Should be fixed now :)

**Pull request merged**
